### ISSUE TITLE
Extension not working on vue2

### ISSUE THREAD

**Issue by felixdenoix** [vue-youtube/vue-youtube#22]
Hi !

While re-working an old project, I've tried to include the library in a vue2 project without success. I know vue2 is EOL and not maintained anymore but as the readme stated that the lib was woking on both vue 2 & 3, and that it works really well on vue3 I tried my luck.

It seems that there is an issue during the component registration and the component is not rendered.  The following error is thrown:

```
Uncaught TypeError: r.provide is not a function
    at Object.install (index.js:12:1)
    at Vue.use (vue.runtime.esm.js:5808:1)
    (...)
```

I've created a codesandbox reproduction here: https://codesandbox.io/p/sandbox/broken-fire-wk68jf?workspaceId=abfa27a5-2bc8-4627-8d58-a8c3f78b090f

Regards

**Comment by Techassi** [comment]
I will take a look and see what I can do. 

Technically it _should_ just work because I use `vue-demi`, but seems like you hit a weird error.

**Comment by felixdenoix** [comment]
Cheers !
Had to setup the project to handle the nullish coalescing operator also but it’s related to the babel version used by the vue-cli if I’m not mistaken.
